export const SimulatedData = [
  {
    id: 1,
    firstName: 'Michał',
    lastName: 'Górecki',
    courseCompletion: 5,
    courseEngagement: 5,
    projectDegree: 4,
    teamProjectDegree: 5,
    expectedTypeWork: 'Zdalnie',
    targetWorkCity: null,
    expectedContractType: 'B2B',
    expectedSalary: 1000,
    canTakeApprenticeship: 'Nie',
    workExperience: 0,
  },
  {
    id: 2,
    firstName: 'Jakub',
    lastName: 'Testowy',
    courseCompletion: 5,
    courseEngagement: 5,
    projectDegree: 5,
    teamProjectDegree: 5,
    expectedTypeWork: 'Biuro',
    targetWorkCity: 'Warszawa',
    expectedContractType: 'Umowa o pracę',
    expectedSalary: 15000,
    canTakeApprenticeship: 'Nie',
    workExperience: 12,
  },
  {
    id: 3,
    firstName: 'Jan',
    lastName: 'Jankowski',
    courseCompletion: 3,
    courseEngagement: 3,
    projectDegree: 3,
    teamProjectDegree: 3,
    expectedTypeWork: 'Biuro',
    targetWorkCity: 'Kielce',
    expectedContractType: 'Umowa o pracę',
    expectedSalary: 5000,
    canTakeApprenticeship: 'Nie',
    workExperience: 3,
  },
  {
    id: 2,
    firstName: 'Ewa',
    lastName: 'Ewalska',
    courseCompletion: 4,
    courseEngagement: 4,
    projectDegree: 4,
    teamProjectDegree: 4,
    expectedTypeWork: 'Dom',
    targetWorkCity: 'Szczecin',
    expectedContractType: 'Umowa o pracę',
    expectedSalary: 3000,
    canTakeApprenticeship: 'Tak',
    workExperience: 1,
  },
  {
    id: 5,
    firstName: 'Agata',
    lastName: 'Śmiszek',
    courseCompletion: 2,
    courseEngagement: 2,
    projectDegree: 2,
    teamProjectDegree: 1,
    expectedTypeWork: 'Biuro',
    targetWorkCity: 'Lublin',
    expectedContractType: 'B2B',
    expectedSalary: 5000,
    canTakeApprenticeship: 'Tak',
    workExperience: 3,
  },
  {
    id: 6,
    firstName: 'Mścisław',
    lastName: 'Wojobolski',
    courseCompletion: 4,
    courseEngagement: 3,
    projectDegree: 1,
    teamProjectDegree: 5,
    expectedTypeWork: 'Dom',
    targetWorkCity: 'Gdańsk',
    expectedContractType: 'Umowa o pracę',
    expectedSalary: 35000,
    canTakeApprenticeship: 'Nie',
    workExperience: 36,
  },
];
